### ISSUE TITLE
iconv(3) + EUC-JP causes application crash

### ISSUE THREAD

**Issue by ikazont** [ikazont/netbsd#121]
**[Original report](https://bitbucket.org/tnozaki/netbsd/issues/121) by Takehiko NOZAKI (Bitbucket: [tnozaki](https://bitbucket.org/tnozaki), GitHub: [ikazont](https://github.com/ikazont)).**

----------------------------------------

```
#!shell
$ LANG=ja_JP.eucJP gdb /usr/bin/msgfmt
Starting program: /usr/bin/msgfmt --version
msgfmt (GNU gettext-tools) 0.14.4

Program received signal SIGSEGV, Segmentation fault.
0x00007f7ff6c00e61 in _citrus_EUC_encode (ei=0x7f7ff7b0f160, s=0x0, n=0, wc=67 L'C\000\000\000', psenc=0x7f7ff7b350d0,
    nresult=0x7f7fffffc8c8) at /usr/src/lib/libc/citrus/modules/citrus_euc.c:224
warning: Source file is more recent than executable.
224                     if (n < 1)
(gdb) bt
#0  0x00007f7ff6c00e61 in _citrus_EUC_encode (ei=0x7f7ff7b0f160, s=0x0, n=0, wc=67 L'C\000\000\000', psenc=0x7f7ff7b350d0,
    nresult=0x7f7fffffc8c8) at /usr/src/lib/libc/citrus/modules/citrus_euc.c:224
#1  0x00007f7ff6c0120e in _citrus_EUC_wcrtomb_priv (ei=0x7f7ff7b0f160, s=0x0, n=0, wc=67 L'C\000\000\000', psenc=0x7f7ff7b350d0,
    nresult=0x7f7fffffc8c8) at /usr/src/lib/libc/citrus/modules/citrus_euc.c:323
#2  0x00007f7ff6c02955 in _citrus_EUC_stdenc_cstomb (ce=0x7f7ff7b060e0, s=0x0, n=0, csid=0, idx=67, ps=0x7f7ff7b350d0,
    nresult=0x7f7fffffc8c8) at /usr/src/lib/libc/citrus/citrus_stdenc_template.h:150
#3  0x00007f7ff68013ba in ?? () from /usr/lib/i18n/libiconv_std.so.5.0
#4  0x00007f7ff7052e24 in iconv () from /usr/lib/libc.so.12
#5  0x00007f7ff7805c5e in __gettext_iconv () from /usr/lib/libintl.so.1
#6  0x00007f7ff7804265 in dcngettext () from /usr/lib/libintl.so.1
#7  0x0000000000403c91 in main ()
(gdb)
```

**Comment by ikazont** [comment]
**Original comment by Takehiko NOZAKI (Bitbucket: [tnozaki](https://bitbucket.org/tnozaki), GitHub: [ikazont](https://github.com/ikazont)).**

----------------------------------------

BUGFIX: Issue #121 -- iconv(3) + EUC-JP causes application crash
this bug introduced by <<cset:6d776e8>>.
